# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_catigory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catigory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
