# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171126_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.Category', verbose_name='Категория'),
        ),
    ]
