# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20171126_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.FileField(null=True, upload_to=shop.models.make_upload_path),
        ),
    ]
