# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_prod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.FileField(null=True, upload_to='static/images'),
        ),
    ]
